/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [\srcWithDoc\[ClassName]ServiceGenerated.cs] button
 *
 * Do not edit this file.
 *
 */ 

using CSSPEnums;
using CSSPModels;
using CSSPModels.Resources;
using CSSPServices.Resources;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Security.Principal;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;

namespace CSSPServices
{
    public partial class EmailDistributionListService
    {
        #region Functions private Generated FillEmailDistributionListExtraA
        /// <summary>
        /// Fills items [EmailDistributionListExtraA](CSSPModels.EmailDistributionListExtraA.html) from CSSPDB
        /// </summary>
        /// <returns>IQueryable of EmailDistributionListExtraA</returns>
        private IQueryable<EmailDistributionListExtraA> FillEmailDistributionListExtraA()
        {
             IQueryable<EmailDistributionListExtraA> EmailDistributionListExtraAQuery = (from c in db.EmailDistributionLists
                let CountryText = (from cl in db.TVItemLanguages
                    where cl.TVItemID == c.CountryTVItemID
                    && cl.Language == LanguageRequest
                    select cl.TVText).FirstOrDefault()
                let LastUpdateContactText = (from cl in db.TVItemLanguages
                    where cl.TVItemID == c.LastUpdateContactTVItemID
                    && cl.Language == LanguageRequest
                    select cl.TVText).FirstOrDefault()
                    select new EmailDistributionListExtraA
                    {
                        CountryText = CountryText,
                        LastUpdateContactText = LastUpdateContactText,
                        EmailDistributionListID = c.EmailDistributionListID,
                        CountryTVItemID = c.CountryTVItemID,
                        Ordinal = c.Ordinal,
                        LastUpdateDate_UTC = c.LastUpdateDate_UTC,
                        LastUpdateContactTVItemID = c.LastUpdateContactTVItemID,
                        HasErrors = false,
                        ValidationResults = null,
                    }).AsNoTracking();

            return EmailDistributionListExtraAQuery;
        }
        #endregion Functions private Generated FillEmailDistributionListExtraA

    }
}
