/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [\srcWithDoc\[ClassName]ServiceGenerated.cs] button
 *
 * Do not edit this file.
 *
 */ 

using CSSPEnums;
using CSSPModels;
using CSSPModels.Resources;
using CSSPServices.Resources;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Security.Principal;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;

namespace CSSPServices
{
    public partial class MapInfoPointService
    {
        #region Functions private Generated FillMapInfoPointExtraA
        /// <summary>
        /// Fills items [MapInfoPointExtraA](CSSPModels.MapInfoPointExtraA.html) from CSSPDB
        /// </summary>
        /// <returns>IQueryable of MapInfoPointExtraA</returns>
        private IQueryable<MapInfoPointExtraA> FillMapInfoPointExtraA()
        {
             IQueryable<MapInfoPointExtraA> MapInfoPointExtraAQuery = (from c in db.MapInfoPoints
                let LastUpdateContactText = (from cl in db.TVItemLanguages
                    where cl.TVItemID == c.LastUpdateContactTVItemID
                    && cl.Language == LanguageRequest
                    select cl.TVText).FirstOrDefault()
                    select new MapInfoPointExtraA
                    {
                        LastUpdateContactText = LastUpdateContactText,
                        MapInfoPointID = c.MapInfoPointID,
                        MapInfoID = c.MapInfoID,
                        Ordinal = c.Ordinal,
                        Lat = c.Lat,
                        Lng = c.Lng,
                        LastUpdateDate_UTC = c.LastUpdateDate_UTC,
                        LastUpdateContactTVItemID = c.LastUpdateContactTVItemID,
                        HasErrors = false,
                        ValidationResults = null,
                    }).AsNoTracking();

            return MapInfoPointExtraAQuery;
        }
        #endregion Functions private Generated FillMapInfoPointExtraA

    }
}
