/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [\src\[ClassName]ServiceGenerated.cs] button
 *
 * Do not edit this file.
 *
 */ 

using CSSPEnums;
using CSSPModels;
using CSSPModels.Resources;
using CSSPServices.Resources;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Security.Principal;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;

namespace CSSPServices
{
    public partial class DrogueRunService
    {
        #region Functions private Generated FillDrogueRunExtraA
        private IQueryable<DrogueRunExtraA> FillDrogueRunExtraA()
        {
            Enums enums = new Enums(LanguageRequest);

            List<EnumIDAndText> DrogueTypeEnumList = enums.GetEnumTextOrderedList(typeof(DrogueTypeEnum));

             IQueryable<DrogueRunExtraA> DrogueRunExtraAQuery = (from c in db.DrogueRuns
                let LastUpdateContactText = (from cl in db.TVItemLanguages
                    where cl.TVItemID == c.LastUpdateContactTVItemID
                    && cl.Language == LanguageRequest
                    select cl.TVText).FirstOrDefault()
                let DrogueTypeText = (from e in DrogueTypeEnumList
                    where e.EnumID == (int?)c.DrogueType
                    select e.EnumText).FirstOrDefault()
                    select new DrogueRunExtraA
                    {
                        LastUpdateContactText = LastUpdateContactText,
                        DrogueTypeText = DrogueTypeText,
                        DrogueRunID = c.DrogueRunID,
                        SubsectorTVItemID = c.SubsectorTVItemID,
                        DrogueNumber = c.DrogueNumber,
                        DrogueType = c.DrogueType,
                        RunStartDateTime = c.RunStartDateTime,
                        LastUpdateDate_UTC = c.LastUpdateDate_UTC,
                        LastUpdateContactTVItemID = c.LastUpdateContactTVItemID,
                        HasErrors = false,
                        ValidationResults = null,
                    }).AsNoTracking();

            return DrogueRunExtraAQuery;
        }
        #endregion Functions private Generated FillDrogueRunExtraA

    }
}
