 /* Auto generated from the CSSPCodeWriter.proj by clicking on the [\src\[ClassName]ServiceGenerated.cs] button
 *
 * Do not edit this file.
 *
 */ 

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq;
using System.Collections.Generic;
using CSSPModels;
using CSSPServices;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Reflection;
using CSSPEnums;
using System.Security.Principal;
using System.Globalization;
using CSSPServices.Resources;
using CSSPModels.Resources;
using CSSPEnums.Resources;

namespace CSSPServices.Tests
{
    [TestClass]
    public partial class TVItemServiceTest : TestHelper
    {
        #region Variables
        #endregion Variables

        #region Properties
        //private TVItemService tvItemService { get; set; }
        #endregion Properties

        #region Constructors
        public TVItemServiceTest() : base()
        {
            //tvItemService = new TVItemService(LanguageRequest, dbTestDB, ContactID);
        }
        #endregion Constructors

        #region Tests Generated CRUD
        [TestMethod]
        public void TVItem_CRUD_Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);

                    int count = 0;
                    if (count == 1)
                    {
                        // just so we don't get a warning during compile [The variable 'count' is assigned but its value is never used]
                    }

                    TVItem tvItem = GetFilledRandomTVItem("");

                    // -------------------------------
                    // -------------------------------
                    // CRUD testing
                    // -------------------------------
                    // -------------------------------

                    count = tvItemService.GetTVItemList().Count();

                    Assert.AreEqual(count, (from c in dbTestDB.TVItems select c).Count());

                    tvItemService.Add(tvItem);
                    if (tvItem.HasErrors)
                    {
                        Assert.AreEqual("", tvItem.ValidationResults.FirstOrDefault().ErrorMessage);
                    }
                    Assert.AreEqual(true, tvItemService.GetTVItemList().Where(c => c == tvItem).Any());
                    tvItemService.Update(tvItem);
                    if (tvItem.HasErrors)
                    {
                        Assert.AreEqual("", tvItem.ValidationResults.FirstOrDefault().ErrorMessage);
                    }
                    Assert.AreEqual(count + 1, tvItemService.GetTVItemList().Count());
                    tvItemService.Delete(tvItem);
                    if (tvItem.HasErrors)
                    {
                        Assert.AreEqual("", tvItem.ValidationResults.FirstOrDefault().ErrorMessage);
                    }
                    Assert.AreEqual(count, tvItemService.GetTVItemList().Count());

                }
            }
        }
        #endregion Tests Generated CRUD

        #region Tests Generated Properties
        [TestMethod]
        public void TVItem_Properties_Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);

                    int count = 0;
                    if (count == 1)
                    {
                        // just so we don't get a warning during compile [The variable 'count' is assigned but its value is never used]
                    }

                    count = tvItemService.GetTVItemList().Count();

                    TVItem tvItem = GetFilledRandomTVItem("");

                    // -------------------------------
                    // -------------------------------
                    // Properties testing
                    // -------------------------------
                    // -------------------------------


                    // -----------------------------------
                    // [Key]
                    // Is NOT Nullable
                    // tvItem.TVItemID   (Int32)
                    // -----------------------------------

                    tvItem = null;
                    tvItem = GetFilledRandomTVItem("");
                    tvItem.TVItemID = 0;
                    tvItemService.Update(tvItem);
                    Assert.AreEqual(string.Format(CSSPServicesRes._IsRequired, "TVItemID"), tvItem.ValidationResults.FirstOrDefault().ErrorMessage);

                    tvItem = null;
                    tvItem = GetFilledRandomTVItem("");
                    tvItem.TVItemID = 10000000;
                    tvItemService.Update(tvItem);
                    Assert.AreEqual(string.Format(CSSPServicesRes.CouldNotFind_With_Equal_, "TVItem", "TVItemID", tvItem.TVItemID.ToString()), tvItem.ValidationResults.FirstOrDefault().ErrorMessage);


                    // -----------------------------------
                    // Is NOT Nullable
                    // [Range(0, 100)]
                    // tvItem.TVLevel   (Int32)
                    // -----------------------------------

                    tvItem = null;
                    tvItem = GetFilledRandomTVItem("");
                    tvItem.TVLevel = -1;
                    Assert.AreEqual(false, tvItemService.Add(tvItem));
                    Assert.AreEqual(string.Format(CSSPServicesRes._ValueShouldBeBetween_And_, "TVLevel", "0", "100"), tvItem.ValidationResults.FirstOrDefault().ErrorMessage);
                    Assert.AreEqual(count, tvItemService.GetTVItemList().Count());
                    tvItem = null;
                    tvItem = GetFilledRandomTVItem("");
                    tvItem.TVLevel = 101;
                    Assert.AreEqual(false, tvItemService.Add(tvItem));
                    Assert.AreEqual(string.Format(CSSPServicesRes._ValueShouldBeBetween_And_, "TVLevel", "0", "100"), tvItem.ValidationResults.FirstOrDefault().ErrorMessage);
                    Assert.AreEqual(count, tvItemService.GetTVItemList().Count());

                    // -----------------------------------
                    // Is NOT Nullable
                    // [StringLength(250))]
                    // tvItem.TVPath   (String)
                    // -----------------------------------

                    tvItem = null;
                    tvItem = GetFilledRandomTVItem("TVPath");
                    Assert.AreEqual(false, tvItemService.Add(tvItem));
                    Assert.AreEqual(1, tvItem.ValidationResults.Count());
                    Assert.IsTrue(tvItem.ValidationResults.Where(c => c.ErrorMessage == string.Format(CSSPServicesRes._IsRequired, "TVPath")).Any());
                    Assert.AreEqual(null, tvItem.TVPath);
                    Assert.AreEqual(count, tvItemService.GetTVItemList().Count());

                    tvItem = null;
                    tvItem = GetFilledRandomTVItem("");
                    tvItem.TVPath = GetRandomString("", 251);
                    Assert.AreEqual(false, tvItemService.Add(tvItem));
                    Assert.AreEqual(string.Format(CSSPServicesRes._MaxLengthIs_, "TVPath", "250"), tvItem.ValidationResults.FirstOrDefault().ErrorMessage);
                    Assert.AreEqual(count, tvItemService.GetTVItemList().Count());

                    // -----------------------------------
                    // Is NOT Nullable
                    // [CSSPEnumType]
                    // tvItem.TVType   (TVTypeEnum)
                    // -----------------------------------

                    tvItem = null;
                    tvItem = GetFilledRandomTVItem("");
                    tvItem.TVType = (TVTypeEnum)1000000;
                    tvItemService.Add(tvItem);
                    Assert.AreEqual(string.Format(CSSPServicesRes._IsRequired, "TVType"), tvItem.ValidationResults.FirstOrDefault().ErrorMessage);


                    // -----------------------------------
                    // Is NOT Nullable
                    // [CSSPExist(ExistTypeName = "TVItem", ExistPlurial = "s", ExistFieldID = "TVItemID", AllowableTVtypeList = Root,Address,Area,ClimateSite,Contact,Country,Email,HydrometricSite,Infrastructure,MikeBoundaryConditionWebTide,MikeBoundaryConditionMesh,MikeScenario,MikeSource,Municipality,MWQMSite,PolSourceSite,Province,Sector,Subsector,Tel,MWQMRun,Classification)]
                    // tvItem.ParentID   (Int32)
                    // -----------------------------------

                    tvItem = null;
                    tvItem = GetFilledRandomTVItem("");
                    tvItem.ParentID = 0;
                    tvItemService.Add(tvItem);
                    Assert.AreEqual(string.Format(CSSPServicesRes.CouldNotFind_With_Equal_, "TVItem", "ParentID", tvItem.ParentID.ToString()), tvItem.ValidationResults.FirstOrDefault().ErrorMessage);

                    tvItem = null;
                    tvItem = GetFilledRandomTVItem("");
                    tvItem.ParentID = 37;
                    tvItemService.Add(tvItem);
                    Assert.AreEqual(string.Format(CSSPServicesRes._IsNotOfType_, "ParentID", "Root,Address,Area,ClimateSite,Contact,Country,Email,HydrometricSite,Infrastructure,MikeBoundaryConditionWebTide,MikeBoundaryConditionMesh,MikeScenario,MikeSource,Municipality,MWQMSite,PolSourceSite,Province,Sector,Subsector,Tel,MWQMRun,Classification"), tvItem.ValidationResults.FirstOrDefault().ErrorMessage);


                    // -----------------------------------
                    // Is NOT Nullable
                    // tvItem.IsActive   (Boolean)
                    // -----------------------------------


                    // -----------------------------------
                    // Is NOT Nullable
                    // [CSSPAfter(Year = 1980)]
                    // tvItem.LastUpdateDate_UTC   (DateTime)
                    // -----------------------------------

                    tvItem = null;
                    tvItem = GetFilledRandomTVItem("");
                    tvItem.LastUpdateDate_UTC = new DateTime();
                    tvItemService.Add(tvItem);
                    Assert.AreEqual(string.Format(CSSPServicesRes._IsRequired, "LastUpdateDate_UTC"), tvItem.ValidationResults.FirstOrDefault().ErrorMessage);
                    tvItem = null;
                    tvItem = GetFilledRandomTVItem("");
                    tvItem.LastUpdateDate_UTC = new DateTime(1979, 1, 1);
                    tvItemService.Add(tvItem);
                    Assert.AreEqual(string.Format(CSSPServicesRes._YearShouldBeBiggerThan_, "LastUpdateDate_UTC", "1980"), tvItem.ValidationResults.FirstOrDefault().ErrorMessage);

                    // -----------------------------------
                    // Is NOT Nullable
                    // [CSSPExist(ExistTypeName = "TVItem", ExistPlurial = "s", ExistFieldID = "TVItemID", AllowableTVtypeList = Contact)]
                    // tvItem.LastUpdateContactTVItemID   (Int32)
                    // -----------------------------------

                    tvItem = null;
                    tvItem = GetFilledRandomTVItem("");
                    tvItem.LastUpdateContactTVItemID = 0;
                    tvItemService.Add(tvItem);
                    Assert.AreEqual(string.Format(CSSPServicesRes.CouldNotFind_With_Equal_, "TVItem", "LastUpdateContactTVItemID", tvItem.LastUpdateContactTVItemID.ToString()), tvItem.ValidationResults.FirstOrDefault().ErrorMessage);

                    tvItem = null;
                    tvItem = GetFilledRandomTVItem("");
                    tvItem.LastUpdateContactTVItemID = 1;
                    tvItemService.Add(tvItem);
                    Assert.AreEqual(string.Format(CSSPServicesRes._IsNotOfType_, "LastUpdateContactTVItemID", "Contact"), tvItem.ValidationResults.FirstOrDefault().ErrorMessage);


                    // -----------------------------------
                    // Is NOT Nullable
                    // [NotMapped]
                    // tvItem.HasErrors   (Boolean)
                    // -----------------------------------

                    // No testing requied

                    // -----------------------------------
                    // Is NOT Nullable
                    // [NotMapped]
                    // tvItem.ValidationResults   (IEnumerable`1)
                    // -----------------------------------

                    // No testing requied
                }
            }
        }
        #endregion Tests Generated Properties

        #region Tests Generated for GetTVItemWithTVItemID(tvItem.TVItemID)
        [TestMethod]
        public void GetTVItemWithTVItemID__tvItem_TVItemID__Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);
                    TVItem tvItem = (from c in dbTestDB.TVItems select c).FirstOrDefault();
                    Assert.IsNotNull(tvItem);

                    foreach (string extra in new List<string>() { null, "A", "B", "C", "D", "E" })
                    {
                        tvItemService.Query.Extra = extra;

                        if (string.IsNullOrWhiteSpace(extra))
                        {
                            TVItem tvItemRet = tvItemService.GetTVItemWithTVItemID(tvItem.TVItemID);
                            CheckTVItemFields(new List<TVItem>() { tvItemRet });
                            Assert.AreEqual(tvItem.TVItemID, tvItemRet.TVItemID);
                        }
                        else if (extra == "A")
                        {
                            TVItemExtraA tvItemExtraARet = tvItemService.GetTVItemExtraAWithTVItemID(tvItem.TVItemID);
                            CheckTVItemExtraAFields(new List<TVItemExtraA>() { tvItemExtraARet });
                            Assert.AreEqual(tvItem.TVItemID, tvItemExtraARet.TVItemID);
                        }
                        else if (extra == "B")
                        {
                            TVItemExtraB tvItemExtraBRet = tvItemService.GetTVItemExtraBWithTVItemID(tvItem.TVItemID);
                            CheckTVItemExtraBFields(new List<TVItemExtraB>() { tvItemExtraBRet });
                            Assert.AreEqual(tvItem.TVItemID, tvItemExtraBRet.TVItemID);
                        }
                        else
                        {
                            //Assert.AreEqual(true, false);
                        }
                    }
                }
            }
        }
        #endregion Tests Generated for GetTVItemWithTVItemID(tvItem.TVItemID)

        #region Tests Generated for GetTVItemList()
        [TestMethod]
        public void GetTVItemList_Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);
                    TVItem tvItem = (from c in dbTestDB.TVItems select c).FirstOrDefault();
                    Assert.IsNotNull(tvItem);

                    List<TVItem> tvItemDirectQueryList = new List<TVItem>();
                    tvItemDirectQueryList = (from c in dbTestDB.TVItems select c).Take(200).ToList();

                    foreach (string extra in new List<string>() { null, "A", "B", "C", "D", "E" })
                    {
                        tvItemService.Query.Extra = extra;

                        if (string.IsNullOrWhiteSpace(extra))
                        {
                            List<TVItem> tvItemList = new List<TVItem>();
                            tvItemList = tvItemService.GetTVItemList().ToList();
                            CheckTVItemFields(tvItemList);
                        }
                        else if (extra == "A")
                        {
                            List<TVItemExtraA> tvItemExtraAList = new List<TVItemExtraA>();
                            tvItemExtraAList = tvItemService.GetTVItemExtraAList().ToList();
                            CheckTVItemExtraAFields(tvItemExtraAList);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraAList.Count);
                        }
                        else if (extra == "B")
                        {
                            List<TVItemExtraB> tvItemExtraBList = new List<TVItemExtraB>();
                            tvItemExtraBList = tvItemService.GetTVItemExtraBList().ToList();
                            CheckTVItemExtraBFields(tvItemExtraBList);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraBList.Count);
                        }
                        else
                        {
                            //Assert.AreEqual(true, false);
                        }
                    }
                }
            }
        }
        #endregion Tests Generated for GetTVItemList()

        #region Tests Generated for GetTVItemList() Skip Take
        [TestMethod]
        public void GetTVItemList_Skip_Take_Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    foreach (string extra in new List<string>() { null, "A", "B", "C", "D", "E" })
                    {
                        TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);

                        tvItemService.Query = tvItemService.FillQuery(typeof(TVItem), culture.TwoLetterISOLanguageName, 1, 1, "", "", "", extra);

                        List<TVItem> tvItemDirectQueryList = new List<TVItem>();
                        tvItemDirectQueryList = (from c in dbTestDB.TVItems select c).Skip(1).Take(1).ToList();

                        if (string.IsNullOrWhiteSpace(extra))
                        {
                            List<TVItem> tvItemList = new List<TVItem>();
                            tvItemList = tvItemService.GetTVItemList().ToList();
                            CheckTVItemFields(tvItemList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemList[0].TVItemID);
                        }
                        else if (extra == "A")
                        {
                            List<TVItemExtraA> tvItemExtraAList = new List<TVItemExtraA>();
                            tvItemExtraAList = tvItemService.GetTVItemExtraAList().ToList();
                            CheckTVItemExtraAFields(tvItemExtraAList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraAList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraAList.Count);
                        }
                        else if (extra == "B")
                        {
                            List<TVItemExtraB> tvItemExtraBList = new List<TVItemExtraB>();
                            tvItemExtraBList = tvItemService.GetTVItemExtraBList().ToList();
                            CheckTVItemExtraBFields(tvItemExtraBList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraBList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraBList.Count);
                        }
                        else
                        {
                            //Assert.AreEqual(true, false);
                        }
                    }
                }
            }
        }
        #endregion Tests Generated for GetTVItemList() Skip Take

        #region Tests Generated for GetTVItemList() Skip Take Asc
        [TestMethod]
        public void GetTVItemList_Skip_Take_Asc_Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    foreach (string extra in new List<string>() { null, "A", "B", "C", "D", "E" })
                    {
                        TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);

                        tvItemService.Query = tvItemService.FillQuery(typeof(TVItem), culture.TwoLetterISOLanguageName, 1, 1,  "TVItemID", "", "", extra);

                        List<TVItem> tvItemDirectQueryList = new List<TVItem>();
                        tvItemDirectQueryList = (from c in dbTestDB.TVItems select c).OrderBy(c => c.TVItemID).Skip(1).Take(1).ToList();

                        if (string.IsNullOrWhiteSpace(extra))
                        {
                            List<TVItem> tvItemList = new List<TVItem>();
                            tvItemList = tvItemService.GetTVItemList().ToList();
                            CheckTVItemFields(tvItemList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemList[0].TVItemID);
                        }
                        else if (extra == "A")
                        {
                            List<TVItemExtraA> tvItemExtraAList = new List<TVItemExtraA>();
                            tvItemExtraAList = tvItemService.GetTVItemExtraAList().ToList();
                            CheckTVItemExtraAFields(tvItemExtraAList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraAList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraAList.Count);
                        }
                        else if (extra == "B")
                        {
                            List<TVItemExtraB> tvItemExtraBList = new List<TVItemExtraB>();
                            tvItemExtraBList = tvItemService.GetTVItemExtraBList().ToList();
                            CheckTVItemExtraBFields(tvItemExtraBList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraBList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraBList.Count);
                        }
                        else
                        {
                            //Assert.AreEqual(true, false);
                        }
                    }
                }
            }
        }
        #endregion Tests Generated for GetTVItemList() Skip Take Asc

        #region Tests Generated for GetTVItemList() Skip Take 2 Asc
        [TestMethod]
        public void GetTVItemList_Skip_Take_2Asc_Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    foreach (string extra in new List<string>() { null, "A", "B", "C", "D", "E" })
                    {
                        TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);

                        tvItemService.Query = tvItemService.FillQuery(typeof(TVItem), culture.TwoLetterISOLanguageName, 1, 1, "TVItemID,TVLevel", "", "", extra);

                        List<TVItem> tvItemDirectQueryList = new List<TVItem>();
                        tvItemDirectQueryList = (from c in dbTestDB.TVItems select c).OrderBy(c => c.TVItemID).ThenBy(c => c.TVLevel).Skip(1).Take(1).ToList();

                        if (string.IsNullOrWhiteSpace(extra))
                        {
                            List<TVItem> tvItemList = new List<TVItem>();
                            tvItemList = tvItemService.GetTVItemList().ToList();
                            CheckTVItemFields(tvItemList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemList[0].TVItemID);
                        }
                        else if (extra == "A")
                        {
                            List<TVItemExtraA> tvItemExtraAList = new List<TVItemExtraA>();
                            tvItemExtraAList = tvItemService.GetTVItemExtraAList().ToList();
                            CheckTVItemExtraAFields(tvItemExtraAList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraAList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraAList.Count);
                        }
                        else if (extra == "B")
                        {
                            List<TVItemExtraB> tvItemExtraBList = new List<TVItemExtraB>();
                            tvItemExtraBList = tvItemService.GetTVItemExtraBList().ToList();
                            CheckTVItemExtraBFields(tvItemExtraBList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraBList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraBList.Count);
                        }
                        else
                        {
                            //Assert.AreEqual(true, false);
                        }
                    }
                }
            }
        }
        #endregion Tests Generated for GetTVItemList() Skip Take 2 Asc

        #region Tests Generated for GetTVItemList() Skip Take Asc Where
        [TestMethod]
        public void GetTVItemList_Skip_Take_Asc_Where_Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    foreach (string extra in new List<string>() { null, "A", "B", "C", "D", "E" })
                    {
                        TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);

                        tvItemService.Query = tvItemService.FillQuery(typeof(TVItem), culture.TwoLetterISOLanguageName, 0, 1, "TVItemID", "", "TVItemID,EQ,4", "");

                        List<TVItem> tvItemDirectQueryList = new List<TVItem>();
                        tvItemDirectQueryList = (from c in dbTestDB.TVItems select c).Where(c => c.TVItemID == 4).OrderBy(c => c.TVItemID).Skip(0).Take(1).ToList();

                        if (string.IsNullOrWhiteSpace(extra))
                        {
                            List<TVItem> tvItemList = new List<TVItem>();
                            tvItemList = tvItemService.GetTVItemList().ToList();
                            CheckTVItemFields(tvItemList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemList[0].TVItemID);
                        }
                        else if (extra == "A")
                        {
                            List<TVItemExtraA> tvItemExtraAList = new List<TVItemExtraA>();
                            tvItemExtraAList = tvItemService.GetTVItemExtraAList().ToList();
                            CheckTVItemExtraAFields(tvItemExtraAList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraAList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraAList.Count);
                        }
                        else if (extra == "B")
                        {
                            List<TVItemExtraB> tvItemExtraBList = new List<TVItemExtraB>();
                            tvItemExtraBList = tvItemService.GetTVItemExtraBList().ToList();
                            CheckTVItemExtraBFields(tvItemExtraBList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraBList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraBList.Count);
                        }
                        else
                        {
                            //Assert.AreEqual(true, false);
                        }
                    }
                }
            }
        }
        #endregion Tests Generated for GetTVItemList() Skip Take Asc Where

        #region Tests Generated for GetTVItemList() Skip Take Asc 2 Where
        [TestMethod]
        public void GetTVItemList_Skip_Take_Asc_2Where_Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    foreach (string extra in new List<string>() { null, "A", "B", "C", "D", "E" })
                    {
                        TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);

                        tvItemService.Query = tvItemService.FillQuery(typeof(TVItem), culture.TwoLetterISOLanguageName, 0, 1, "TVItemID", "", "TVItemID,GT,2|TVItemID,LT,5", "");

                        List<TVItem> tvItemDirectQueryList = new List<TVItem>();
                        tvItemDirectQueryList = (from c in dbTestDB.TVItems select c).Where(c => c.TVItemID > 2 && c.TVItemID < 5).Skip(0).Take(1).OrderBy(c => c.TVItemID).ToList();

                        if (string.IsNullOrWhiteSpace(extra))
                        {
                            List<TVItem> tvItemList = new List<TVItem>();
                            tvItemList = tvItemService.GetTVItemList().ToList();
                            CheckTVItemFields(tvItemList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemList[0].TVItemID);
                        }
                        else if (extra == "A")
                        {
                            List<TVItemExtraA> tvItemExtraAList = new List<TVItemExtraA>();
                            tvItemExtraAList = tvItemService.GetTVItemExtraAList().ToList();
                            CheckTVItemExtraAFields(tvItemExtraAList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraAList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraAList.Count);
                        }
                        else if (extra == "B")
                        {
                            List<TVItemExtraB> tvItemExtraBList = new List<TVItemExtraB>();
                            tvItemExtraBList = tvItemService.GetTVItemExtraBList().ToList();
                            CheckTVItemExtraBFields(tvItemExtraBList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraBList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraBList.Count);
                        }
                        else
                        {
                            //Assert.AreEqual(true, false);
                        }
                    }
                }
            }
        }
        #endregion Tests Generated for GetTVItemList() Skip Take Asc 2 Where

        #region Tests Generated for GetTVItemList() Skip Take Desc
        [TestMethod]
        public void GetTVItemList_Skip_Take_Desc_Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    foreach (string extra in new List<string>() { null, "A", "B", "C", "D", "E" })
                    {
                        TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);

                        tvItemService.Query = tvItemService.FillQuery(typeof(TVItem), culture.TwoLetterISOLanguageName, 1, 1, "", "TVItemID", "", extra);

                        List<TVItem> tvItemDirectQueryList = new List<TVItem>();
                        tvItemDirectQueryList = (from c in dbTestDB.TVItems select c).OrderByDescending(c => c.TVItemID).Skip(1).Take(1).ToList();

                        if (string.IsNullOrWhiteSpace(extra))
                        {
                            List<TVItem> tvItemList = new List<TVItem>();
                            tvItemList = tvItemService.GetTVItemList().ToList();
                            CheckTVItemFields(tvItemList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemList[0].TVItemID);
                        }
                        else if (extra == "A")
                        {
                            List<TVItemExtraA> tvItemExtraAList = new List<TVItemExtraA>();
                            tvItemExtraAList = tvItemService.GetTVItemExtraAList().ToList();
                            CheckTVItemExtraAFields(tvItemExtraAList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraAList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraAList.Count);
                        }
                        else if (extra == "B")
                        {
                            List<TVItemExtraB> tvItemExtraBList = new List<TVItemExtraB>();
                            tvItemExtraBList = tvItemService.GetTVItemExtraBList().ToList();
                            CheckTVItemExtraBFields(tvItemExtraBList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraBList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraBList.Count);
                        }
                        else
                        {
                            //Assert.AreEqual(true, false);
                        }
                    }
                }
            }
        }
        #endregion Tests Generated for GetTVItemList() Skip Take Desc

        #region Tests Generated for GetTVItemList() Skip Take 2 Desc
        [TestMethod]
        public void GetTVItemList_Skip_Take_2Desc_Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    foreach (string extra in new List<string>() { null, "A", "B", "C", "D", "E" })
                    {
                        TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);

                        tvItemService.Query = tvItemService.FillQuery(typeof(TVItem), culture.TwoLetterISOLanguageName, 1, 1, "", "TVItemID,TVLevel", "", extra);

                        List<TVItem> tvItemDirectQueryList = new List<TVItem>();
                        tvItemDirectQueryList = (from c in dbTestDB.TVItems select c).OrderByDescending(c => c.TVItemID).ThenByDescending(c => c.TVLevel).Skip(1).Take(1).ToList();

                        if (string.IsNullOrWhiteSpace(extra))
                        {
                            List<TVItem> tvItemList = new List<TVItem>();
                            tvItemList = tvItemService.GetTVItemList().ToList();
                            CheckTVItemFields(tvItemList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemList[0].TVItemID);
                        }
                        else if (extra == "A")
                        {
                            List<TVItemExtraA> tvItemExtraAList = new List<TVItemExtraA>();
                            tvItemExtraAList = tvItemService.GetTVItemExtraAList().ToList();
                            CheckTVItemExtraAFields(tvItemExtraAList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraAList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraAList.Count);
                        }
                        else if (extra == "B")
                        {
                            List<TVItemExtraB> tvItemExtraBList = new List<TVItemExtraB>();
                            tvItemExtraBList = tvItemService.GetTVItemExtraBList().ToList();
                            CheckTVItemExtraBFields(tvItemExtraBList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraBList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraBList.Count);
                        }
                        else
                        {
                            //Assert.AreEqual(true, false);
                        }
                    }
                }
            }
        }
        #endregion Tests Generated for GetTVItemList() Skip Take 2 Desc

        #region Tests Generated for GetTVItemList() Skip Take Desc Where
        [TestMethod]
        public void GetTVItemList_Skip_Take_Desc_Where_Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    foreach (string extra in new List<string>() { null, "A", "B", "C", "D", "E" })
                    {
                        TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);

                        tvItemService.Query = tvItemService.FillQuery(typeof(TVItem), culture.TwoLetterISOLanguageName, 0, 1, "TVItemID", "", "TVItemID,EQ,4", "");

                        List<TVItem> tvItemDirectQueryList = new List<TVItem>();
                        tvItemDirectQueryList = (from c in dbTestDB.TVItems select c).Where(c => c.TVItemID == 4).OrderByDescending(c => c.TVItemID).Skip(0).Take(1).ToList();

                        if (string.IsNullOrWhiteSpace(extra))
                        {
                            List<TVItem> tvItemList = new List<TVItem>();
                            tvItemList = tvItemService.GetTVItemList().ToList();
                            CheckTVItemFields(tvItemList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemList[0].TVItemID);
                        }
                        else if (extra == "A")
                        {
                            List<TVItemExtraA> tvItemExtraAList = new List<TVItemExtraA>();
                            tvItemExtraAList = tvItemService.GetTVItemExtraAList().ToList();
                            CheckTVItemExtraAFields(tvItemExtraAList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraAList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraAList.Count);
                        }
                        else if (extra == "B")
                        {
                            List<TVItemExtraB> tvItemExtraBList = new List<TVItemExtraB>();
                            tvItemExtraBList = tvItemService.GetTVItemExtraBList().ToList();
                            CheckTVItemExtraBFields(tvItemExtraBList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraBList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraBList.Count);
                        }
                        else
                        {
                            //Assert.AreEqual(true, false);
                        }
                    }
                }
            }
        }
        #endregion Tests Generated for GetTVItemList() Skip Take Desc Where

        #region Tests Generated for GetTVItemList() Skip Take Desc 2 Where
        [TestMethod]
        public void GetTVItemList_Skip_Take_Desc_2Where_Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    foreach (string extra in new List<string>() { null, "A", "B", "C", "D", "E" })
                    {
                        TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);

                        tvItemService.Query = tvItemService.FillQuery(typeof(TVItem), culture.TwoLetterISOLanguageName, 0, 1, "", "TVItemID", "TVItemID,GT,2|TVItemID,LT,5", "");

                        List<TVItem> tvItemDirectQueryList = new List<TVItem>();
                        tvItemDirectQueryList = (from c in dbTestDB.TVItems select c).Where(c => c.TVItemID > 2 && c.TVItemID < 5).OrderByDescending(c => c.TVItemID).Skip(0).Take(1).ToList();

                        if (string.IsNullOrWhiteSpace(extra))
                        {
                            List<TVItem> tvItemList = new List<TVItem>();
                            tvItemList = tvItemService.GetTVItemList().ToList();
                            CheckTVItemFields(tvItemList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemList[0].TVItemID);
                        }
                        else if (extra == "A")
                        {
                            List<TVItemExtraA> tvItemExtraAList = new List<TVItemExtraA>();
                            tvItemExtraAList = tvItemService.GetTVItemExtraAList().ToList();
                            CheckTVItemExtraAFields(tvItemExtraAList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraAList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraAList.Count);
                        }
                        else if (extra == "B")
                        {
                            List<TVItemExtraB> tvItemExtraBList = new List<TVItemExtraB>();
                            tvItemExtraBList = tvItemService.GetTVItemExtraBList().ToList();
                            CheckTVItemExtraBFields(tvItemExtraBList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraBList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraBList.Count);
                        }
                        else
                        {
                            //Assert.AreEqual(true, false);
                        }
                    }
                }
            }
        }
        #endregion Tests Generated for GetTVItemList() Skip Take Desc 2 Where

        #region Tests Generated for GetTVItemList() 2 Where
        [TestMethod]
        public void GetTVItemList_2Where_Test()
        {
            foreach (CultureInfo culture in AllowableCulture)
            {
                ChangeCulture(culture);

                using (CSSPDBContext dbTestDB = new CSSPDBContext(DatabaseTypeEnum.SqlServerTestDB))
                {
                    foreach (string extra in new List<string>() { null, "A", "B", "C", "D", "E" })
                    {
                        TVItemService tvItemService = new TVItemService(new Query() { Lang = culture.TwoLetterISOLanguageName }, dbTestDB, ContactID);

                        tvItemService.Query = tvItemService.FillQuery(typeof(TVItem), culture.TwoLetterISOLanguageName, 0, 10000, "", "", "TVItemID,GT,2|TVItemID,LT,5", extra);

                        List<TVItem> tvItemDirectQueryList = new List<TVItem>();
                        tvItemDirectQueryList = (from c in dbTestDB.TVItems select c).Where(c => c.TVItemID > 2 && c.TVItemID < 5).ToList();

                        if (string.IsNullOrWhiteSpace(extra))
                        {
                            List<TVItem> tvItemList = new List<TVItem>();
                            tvItemList = tvItemService.GetTVItemList().ToList();
                            CheckTVItemFields(tvItemList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemList[0].TVItemID);
                        }
                        else if (extra == "A")
                        {
                            List<TVItemExtraA> tvItemExtraAList = new List<TVItemExtraA>();
                            tvItemExtraAList = tvItemService.GetTVItemExtraAList().ToList();
                            CheckTVItemExtraAFields(tvItemExtraAList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraAList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraAList.Count);
                        }
                        else if (extra == "B")
                        {
                            List<TVItemExtraB> tvItemExtraBList = new List<TVItemExtraB>();
                            tvItemExtraBList = tvItemService.GetTVItemExtraBList().ToList();
                            CheckTVItemExtraBFields(tvItemExtraBList);
                            Assert.AreEqual(tvItemDirectQueryList[0].TVItemID, tvItemExtraBList[0].TVItemID);
                            Assert.AreEqual(tvItemDirectQueryList.Count, tvItemExtraBList.Count);
                        }
                        else
                        {
                            //Assert.AreEqual(true, false);
                        }
                    }
                }
            }
        }
        #endregion Tests Generated for GetTVItemList() 2 Where

        #region Functions private
        private void CheckTVItemFields(List<TVItem> tvItemList)
        {
            Assert.IsNotNull(tvItemList[0].TVItemID);
            Assert.IsNotNull(tvItemList[0].TVLevel);
            Assert.IsFalse(string.IsNullOrWhiteSpace(tvItemList[0].TVPath));
            Assert.IsNotNull(tvItemList[0].TVType);
            Assert.IsNotNull(tvItemList[0].ParentID);
            Assert.IsNotNull(tvItemList[0].IsActive);
            Assert.IsNotNull(tvItemList[0].LastUpdateDate_UTC);
            Assert.IsNotNull(tvItemList[0].LastUpdateContactTVItemID);
            Assert.IsNotNull(tvItemList[0].HasErrors);
        }
        private void CheckTVItemExtraAFields(List<TVItemExtraA> tvItemExtraAList)
        {
            Assert.IsFalse(string.IsNullOrWhiteSpace(tvItemExtraAList[0].TVItemText));
            Assert.IsFalse(string.IsNullOrWhiteSpace(tvItemExtraAList[0].LastUpdateContactText));
            if (!string.IsNullOrWhiteSpace(tvItemExtraAList[0].TVTypeText))
            {
                Assert.IsFalse(string.IsNullOrWhiteSpace(tvItemExtraAList[0].TVTypeText));
            }
            Assert.IsNotNull(tvItemExtraAList[0].TVItemID);
            Assert.IsNotNull(tvItemExtraAList[0].TVLevel);
            Assert.IsFalse(string.IsNullOrWhiteSpace(tvItemExtraAList[0].TVPath));
            Assert.IsNotNull(tvItemExtraAList[0].TVType);
            Assert.IsNotNull(tvItemExtraAList[0].ParentID);
            Assert.IsNotNull(tvItemExtraAList[0].IsActive);
            Assert.IsNotNull(tvItemExtraAList[0].LastUpdateDate_UTC);
            Assert.IsNotNull(tvItemExtraAList[0].LastUpdateContactTVItemID);
            Assert.IsNotNull(tvItemExtraAList[0].HasErrors);
        }
        private void CheckTVItemExtraBFields(List<TVItemExtraB> tvItemExtraBList)
        {
            if (!string.IsNullOrWhiteSpace(tvItemExtraBList[0].TVItemReportTest))
            {
                Assert.IsFalse(string.IsNullOrWhiteSpace(tvItemExtraBList[0].TVItemReportTest));
            }
            Assert.IsFalse(string.IsNullOrWhiteSpace(tvItemExtraBList[0].TVItemText));
            Assert.IsFalse(string.IsNullOrWhiteSpace(tvItemExtraBList[0].LastUpdateContactText));
            if (!string.IsNullOrWhiteSpace(tvItemExtraBList[0].TVTypeText))
            {
                Assert.IsFalse(string.IsNullOrWhiteSpace(tvItemExtraBList[0].TVTypeText));
            }
            Assert.IsNotNull(tvItemExtraBList[0].TVItemID);
            Assert.IsNotNull(tvItemExtraBList[0].TVLevel);
            Assert.IsFalse(string.IsNullOrWhiteSpace(tvItemExtraBList[0].TVPath));
            Assert.IsNotNull(tvItemExtraBList[0].TVType);
            Assert.IsNotNull(tvItemExtraBList[0].ParentID);
            Assert.IsNotNull(tvItemExtraBList[0].IsActive);
            Assert.IsNotNull(tvItemExtraBList[0].LastUpdateDate_UTC);
            Assert.IsNotNull(tvItemExtraBList[0].LastUpdateContactTVItemID);
            Assert.IsNotNull(tvItemExtraBList[0].HasErrors);
        }
        private TVItem GetFilledRandomTVItem(string OmitPropName)
        {
            TVItem tvItem = new TVItem();

            if (OmitPropName != "TVLevel") tvItem.TVLevel = GetRandomInt(0, 100);
            if (OmitPropName != "TVPath") tvItem.TVPath = GetRandomString("", 5);
            if (OmitPropName != "TVType") tvItem.TVType = (TVTypeEnum)GetRandomEnumType(typeof(TVTypeEnum));
            if (OmitPropName != "ParentID") tvItem.ParentID = 1;
            if (OmitPropName != "IsActive") tvItem.IsActive = true;
            if (OmitPropName != "LastUpdateDate_UTC") tvItem.LastUpdateDate_UTC = new DateTime(2005, 3, 6);
            if (OmitPropName != "LastUpdateContactTVItemID") tvItem.LastUpdateContactTVItemID = 2;

            return tvItem;
        }
        #endregion Functions private
    }
}
