//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPServices.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServicesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServicesRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPServices.Resources.ServicesRes", typeof(ServicesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was added to website by {1}..
        /// </summary>
        public static string _AddedInWebSiteBy_ {
            get {
                return ResourceManager.GetString("_AddedInWebSiteBy_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        public static string _AlreadyExists {
            get {
                return ResourceManager.GetString("_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} are not identical..
        /// </summary>
        public static string _And_AreNotIdentical {
            get {
                return ResourceManager.GetString("_And_AreNotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        public static string _DoesNotExist {
            get {
                return ResourceManager.GetString("_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} email not valid..
        /// </summary>
        public static string _EmailNotWellFormed {
            get {
                return ResourceManager.GetString("_EmailNotWellFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has to be unique..
        /// </summary>
        public static string _HasToBeUnique {
            get {
                return ResourceManager.GetString("_HasToBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already taken..
        /// </summary>
        public static string _IsAlreadyTaken {
            get {
                return ResourceManager.GetString("_IsAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} est déjà pris..
        /// </summary>
        public static string _IsAlreadyTaken1 {
            get {
                return ResourceManager.GetString("_IsAlreadyTaken1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is later than {1}..
        /// </summary>
        public static string _IsLaterThan_ {
            get {
                return ResourceManager.GetString("_IsLaterThan_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid email.
        /// </summary>
        public static string _IsNotAValidEmail {
            get {
                return ResourceManager.GetString("_IsNotAValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not composed of {1} parts..
        /// </summary>
        public static string _IsNotComposedOf_Parts {
            get {
                return ResourceManager.GetString("_IsNotComposedOf_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null or empty.
        /// </summary>
        public static string _IsNullOrEmpty {
            get {
                return ResourceManager.GetString("_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string _IsRequired {
            get {
                return ResourceManager.GetString("_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} length should be between {1} and {2}.
        /// </summary>
        public static string _LengthShouldBeBetween_And_ {
            get {
                return ResourceManager.GetString("_LengthShouldBeBetween_And_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} maximum length is {1}..
        /// </summary>
        public static string _MaxLengthIs_ {
            get {
                return ResourceManager.GetString("_MaxLengthIs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} maximum value is {1}.
        /// </summary>
        public static string _MaxValueIs_ {
            get {
                return ResourceManager.GetString("_MaxValueIs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minimum length is {1}..
        /// </summary>
        public static string _MinLengthIs_ {
            get {
                return ResourceManager.GetString("_MinLengthIs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minimum value is {1}.
        /// </summary>
        public static string _MinValueIs_ {
            get {
                return ResourceManager.GetString("_MinValueIs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was registered on the website..
        /// </summary>
        public static string _RegisteredAndAddedInWebSite {
            get {
                return ResourceManager.GetString("_RegisteredAndAddedInWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} value should be between {1} and {2}.
        /// </summary>
        public static string _ValueShouldBeBetween_And_ {
            get {
                return ResourceManager.GetString("_ValueShouldBeBetween_And_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated email from server..
        /// </summary>
        public static string AutoEmailFromServer {
            get {
                return ResourceManager.GetString("AutoEmailFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code {0} for email {1} does not exist..
        /// </summary>
        public static string Code_ForEmail_DoesNotExist {
            get {
                return ResourceManager.GetString("Code_ForEmail_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeEmail.
        /// </summary>
        public static string CodeEmail {
            get {
                return ResourceManager.GetString("CodeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is:.
        /// </summary>
        public static string CodeIs {
            get {
                return ResourceManager.GetString("CodeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code needs to be 8 characters.
        /// </summary>
        public static string CodeNeedsToBe8Characters {
            get {
                return ResourceManager.GetString("CodeNeedsToBe8Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add {0}. Error: {1}.
        /// </summary>
        public static string CouldNotAdd_Error_ {
            get {
                return ResourceManager.GetString("CouldNotAdd_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0}..
        /// </summary>
        public static string CouldNotFind_ {
            get {
                return ResourceManager.GetString("CouldNotFind_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0} with {1} equal {2}..
        /// </summary>
        public static string CouldNotFind_With_Equal_ {
            get {
                return ResourceManager.GetString("CouldNotFind_With_Equal_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Root.
        /// </summary>
        public static string CouldNotFindRoot {
            get {
                return ResourceManager.GetString("CouldNotFindRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was not sent. Error: {0}.
        /// </summary>
        public static string EmailWasNotSent_ {
            get {
                return ResourceManager.GetString("EmailWasNotSent_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length of password hash. Should be 64 bytes..
        /// </summary>
        public static string InvalidLengthOfPasswordHashShouldBe64Bytes {
            get {
                return ResourceManager.GetString("InvalidLengthOfPasswordHashShouldBe64Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length of password salt. Should be 128 bytes..
        /// </summary>
        public static string InvalidLengthOfPasswordSaltShouldBe128Bytes {
            get {
                return ResourceManager.GetString("InvalidLengthOfPasswordSaltShouldBe128Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to be logged in.
        /// </summary>
        public static string NeedToBeLoggedIn {
            get {
                return ResourceManager.GetString("NeedToBeLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to change contact information.
        /// </summary>
        public static string NotAllowedToChangeContactInformation {
            get {
                return ResourceManager.GetString("NotAllowedToChangeContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only administrators can manage accounts of users..
        /// </summary>
        public static string OnlyAdministratorsCanManageUsers {
            get {
                return ResourceManager.GetString("OnlyAdministratorsCanManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the following unique code while resetting your password for this login email..
        /// </summary>
        public static string PlsUseFollowingUniqueCodeEtc {
            get {
                return ResourceManager.GetString("PlsUseFollowingUniqueCodeEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required information to change your password.
        /// </summary>
        public static string RequiredInformationToChangeYourPassword {
            get {
                return ResourceManager.GetString("RequiredInformationToChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add first {0} requires {1} table to be empty.
        /// </summary>
        public static string ToAddFirst_Requires_TableToBeEmpty {
            get {
                return ResourceManager.GetString("ToAddFirst_Requires_TableToBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVItem &apos;Root&apos; should be the first one added.
        /// </summary>
        public static string TVItemRootShouldBeTheFirstOneAdded {
            get {
                return ResourceManager.GetString("TVItemRootShouldBeTheFirstOneAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with LoginEmail {0} already exist.
        /// </summary>
        public static string UserWithLoginEmail_AlreadyExist {
            get {
                return ResourceManager.GetString("UserWithLoginEmail_AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been added to Web Site by {0}..
        /// </summary>
        public static string YouBeenAddedInWebSiteBy_ {
            get {
                return ResourceManager.GetString("YouBeenAddedInWebSiteBy_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is:.
        /// </summary>
        public static string YourEmailIs {
            get {
                return ResourceManager.GetString("YourEmailIs", resourceCulture);
            }
        }
    }
}
